/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Bruno
 */
public class Cliente extends javax.swing.JInternalFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcliente = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        masculino = new javax.swing.JRadioButton();
        feminino = new javax.swing.JRadioButton();
        outros = new javax.swing.JRadioButton();
        nome = new javax.swing.JTextField();
        telefone = new javax.swing.JFormattedTextField();
        cpf = new javax.swing.JFormattedTextField();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        salvar = new javax.swing.JButton();
        editar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        endereco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        rua = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        bairro = new javax.swing.JTextField();
        estado = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        tbcliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbcliente);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(102, 204, 507, 93);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nome");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(59, 38, 50, 16);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CPF");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(59, 83, 40, 16);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Endereço");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(59, 125, 53, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Telefone");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(238, 38, 50, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("RG");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(270, 80, 16, 16);

        buttonGroup1.add(masculino);
        masculino.setText("Masculino");
        getContentPane().add(masculino);
        masculino.setBounds(507, 121, 85, 25);

        buttonGroup1.add(feminino);
        feminino.setText("Feminino");
        getContentPane().add(feminino);
        feminino.setBounds(596, 121, 81, 25);

        buttonGroup1.add(outros);
        outros.setText("Outros");
        getContentPane().add(outros);
        outros.setBounds(681, 121, 67, 25);
        getContentPane().add(nome);
        nome.setBounds(110, 40, 98, 22);

        try {
            telefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(telefone);
        telefone.setBounds(293, 35, 144, 22);

        try {
            cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(cpf);
        cpf.setBounds(110, 80, 102, 22);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField1);
        jFormattedTextField1.setBounds(293, 75, 144, 22);

        salvar.setText("Salvar");
        getContentPane().add(salvar);
        salvar.setBounds(257, 310, 69, 25);

        editar.setText("Editar");
        getContentPane().add(editar);
        editar.setBounds(333, 310, 65, 25);

        excluir.setText("Excluir");
        getContentPane().add(excluir);
        excluir.setBounds(405, 310, 69, 25);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Data de nascimento");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(470, 38, 113, 16);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("E-mail");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(506, 78, 36, 16);
        getContentPane().add(email);
        email.setBounds(583, 75, 117, 22);

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(jFormattedTextField2);
        jFormattedTextField2.setBounds(583, 35, 117, 22);
        getContentPane().add(endereco);
        endereco.setBounds(130, 122, 115, 22);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Cidade");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(263, 125, 39, 16);
        getContentPane().add(cidade);
        cidade.setBounds(307, 122, 118, 22);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Rua");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(70, 168, 22, 15);
        getContentPane().add(rua);
        rua.setBounds(130, 164, 115, 22);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Bairro");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(263, 167, 34, 16);
        getContentPane().add(bairro);
        bairro.setBounds(309, 164, 116, 22);

        estado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione seu estado", "AC", "AL", "AP", "AM", "BA", "CE", "DF", "ES", "GO", "MA", "MT", "MS", "MG", "PA", "PB", "PR", "PI", "RJ", "RN", "RS", "RO", "RR", "SC", "SP", "SE", "TO" }));
        getContentPane().add(estado);
        estado.setBounds(507, 164, 148, 22);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/86669746-vintage-garage-retro-poster.jpg"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 780, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bairro;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField cidade;
    private javax.swing.JFormattedTextField cpf;
    private javax.swing.JButton editar;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JComboBox<String> estado;
    private javax.swing.JButton excluir;
    private javax.swing.JRadioButton feminino;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JTextField nome;
    private javax.swing.JRadioButton outros;
    private javax.swing.JTextField rua;
    private javax.swing.JButton salvar;
    private javax.swing.JTable tbcliente;
    private javax.swing.JFormattedTextField telefone;
    // End of variables declaration//GEN-END:variables
}
