/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Bruno
 */
public class CompraPeca extends javax.swing.JInternalFrame {

    /**
     * Creates new form CompraPeca
     */
    public CompraPeca() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        dtcompra = new javax.swing.JFormattedTextField();
        nomecompra = new javax.swing.JTextField();
        marcacompra = new javax.swing.JTextField();
        valorcompra = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        fornecedorcompra = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantidadecompra = new javax.swing.JTextField();
        salvar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        lotecompra = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setText("Data da compra");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(36, 49, 91, 16);

        jLabel2.setText("Nome da peça");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(294, 52, 82, 16);

        jLabel3.setText("Marca");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(36, 116, 35, 16);

        jLabel4.setText("Valor");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(294, 116, 30, 16);

        try {
            dtcompra.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(dtcompra);
        dtcompra.setBounds(132, 46, 114, 22);
        getContentPane().add(nomecompra);
        nomecompra.setBounds(381, 46, 117, 22);
        getContentPane().add(marcacompra);
        marcacompra.setBounds(132, 113, 114, 22);
        getContentPane().add(valorcompra);
        valorcompra.setBounds(381, 113, 117, 22);

        jLabel5.setText("Fornecedor");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(294, 188, 65, 16);
        getContentPane().add(fornecedorcompra);
        fornecedorcompra.setBounds(377, 185, 121, 22);

        jLabel6.setText("Quantidade");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(36, 188, 65, 16);
        getContentPane().add(quantidadecompra);
        quantidadecompra.setBounds(125, 185, 116, 22);

        salvar.setText("Salvar");
        getContentPane().add(salvar);
        salvar.setBounds(228, 313, 69, 25);

        jLabel7.setText("N° Lote");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(36, 253, 42, 16);
        getContentPane().add(lotecompra);
        lotecompra.setBounds(125, 250, 116, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/49142886-vintage-garage-retro-poster.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 0, 550, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dtcompra;
    private javax.swing.JTextField fornecedorcompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField lotecompra;
    private javax.swing.JTextField marcacompra;
    private javax.swing.JTextField nomecompra;
    private javax.swing.JTextField quantidadecompra;
    private javax.swing.JButton salvar;
    private javax.swing.JTextField valorcompra;
    // End of variables declaration//GEN-END:variables
}
