/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Bruno
 */
public class CriarOS extends javax.swing.JInternalFrame {

    /**
     * Creates new form NewJInternalFrame
     */
    public CriarOS() {
        initComponents();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        dtentrada = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        funcionario = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelapecas = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        dtsaida = new javax.swing.JFormattedTextField();
        adicionar = new javax.swing.JButton();
        remover = new javax.swing.JButton();
        BC = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nomecliente = new javax.swing.JLabel();
        cpfcliente = new javax.swing.JLabel();
        telefonecliente = new javax.swing.JLabel();
        enderecocliente = new javax.swing.JLabel();
        BF = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        jLabel2.setText("Data de entrada");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(82, 109, 92, 16);

        try {
            dtentrada.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(dtentrada);
        dtentrada.setBounds(192, 106, 94, 22);

        jLabel3.setText("Funcionário resposável");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(43, 169, 131, 16);
        jPanel1.add(funcionario);
        funcionario.setBounds(192, 166, 109, 22);

        tabelapecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelapecas);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(111, 258, 452, 105);

        jLabel4.setText("Data de saída prevista");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(311, 109, 127, 16);

        try {
            dtsaida.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(dtsaida);
        dtsaida.setBounds(464, 106, 89, 22);

        adicionar.setText("Adicionar Produto");
        jPanel1.add(adicionar);
        adicionar.setBounds(189, 220, 133, 25);

        remover.setText("Remover Produto");
        jPanel1.add(remover);
        remover.setBounds(361, 220, 131, 25);

        BC.setText("Buscar Cliente");
        BC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BCMouseClicked(evt);
            }
        });
        jPanel1.add(BC);
        BC.setBounds(126, 376, 119, 25);

        jLabel5.setText("Nome:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(82, 17, 38, 21);

        jLabel6.setText("CPF:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(71, 59, 38, 24);

        jLabel7.setText("Telefone:");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(311, 13, 55, 29);

        jLabel1.setText("Endereço:");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(311, 60, 58, 16);
        jPanel1.add(nomecliente);
        nomecliente.setBounds(61, 13, 0, 0);
        jPanel1.add(cpfcliente);
        cpfcliente.setBounds(61, 59, 0, 0);
        jPanel1.add(telefonecliente);
        telefonecliente.setBounds(237, 13, 0, 0);
        jPanel1.add(enderecocliente);
        enderecocliente.setBounds(240, 67, 36, 16);

        BF.setText("Buscar Funcionário");
        jPanel1.add(BF);
        BF.setBounds(257, 376, 141, 25);

        jButton1.setText("Gerar nota fiscal");
        jPanel1.add(jButton1);
        jButton1.setBounds(416, 376, 127, 25);

        jButton2.setText("Salvar");
        jPanel1.add(jButton2);
        jButton2.setBounds(305, 443, 69, 25);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/cartel-oxidado-accion-photoshop.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 680, 480);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BCMouseClicked
        BuscaCliente bc = new BuscaCliente();
        bc.setClosable(true);
        bc.setVisible(true);
        bc.setSelected(500, 500);
        
        
    }//GEN-LAST:event_BCMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BC;
    private javax.swing.JButton BF;
    private javax.swing.JButton adicionar;
    private javax.swing.JLabel cpfcliente;
    private javax.swing.JFormattedTextField dtentrada;
    private javax.swing.JFormattedTextField dtsaida;
    private javax.swing.JLabel enderecocliente;
    private javax.swing.JTextField funcionario;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel nomecliente;
    private javax.swing.JButton remover;
    private javax.swing.JTable tabelapecas;
    private javax.swing.JLabel telefonecliente;
    // End of variables declaration//GEN-END:variables
}
