/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

/**
 *
 * @author Bruno
 */
public class NotaFiscal extends javax.swing.JInternalFrame {

    /**
     * Creates new form NotaFiscal
     */
    public NotaFiscal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dtemissao = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        valor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbpecas = new javax.swing.JTable();
        imprimir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        nome = new javax.swing.JTextField();
        endereco = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        funcionario = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();

        getContentPane().setLayout(null);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Data de emissão");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 34, 95, 16);

        try {
            dtemissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        getContentPane().add(dtemissao);
        dtemissao.setBounds(110, 30, 85, 22);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Valor");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(270, 30, 30, 16);
        getContentPane().add(valor);
        valor.setBounds(304, 31, 121, 22);

        tbpecas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbpecas);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 280, 540, 90);

        imprimir.setText("Imprimir");
        getContentPane().add(imprimir);
        imprimir.setBounds(250, 390, 100, 25);

        jPanel1.setOpaque(false);
        jPanel1.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nome");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 24, 33, 16);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("CPF");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 62, 22, 16);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Endereco");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 93, 53, 16);
        jPanel1.add(nome);
        nome.setBounds(47, 21, 143, 22);
        jPanel1.add(endereco);
        endereco.setBounds(70, 90, 230, 22);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Fone");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(265, 24, 28, 16);

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ##### ####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField1);
        jFormattedTextField1.setBounds(295, 21, 145, 22);

        try {
            jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###-###-###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField2);
        jFormattedTextField2.setBounds(47, 59, 143, 22);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Funcionário Responsável");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 137, 141, 16);
        jPanel1.add(funcionario);
        funcionario.setBounds(160, 130, 129, 22);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data de nascimento");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(310, 90, 113, 16);

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(jFormattedTextField3);
        jFormattedTextField3.setBounds(430, 90, 140, 22);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 57, 610, 170);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/49142886-vintage-garage-retro-poster.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 610, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField dtemissao;
    private javax.swing.JTextField endereco;
    private javax.swing.JTextField funcionario;
    private javax.swing.JButton imprimir;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JTable tbpecas;
    private javax.swing.JTextField valor;
    // End of variables declaration//GEN-END:variables
}
